spring.application.name=TextToAudio

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:ttsdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
elevenlabs.default.voice=CwhRBWXzGAHq8TQ4Fs17
elevenlabs.api.key=${ELEVENLABS_API_KEY}
